### ISSUE TITLE
Clarify licensing between `LICENSE` and `COPYING`

### ISSUE THREAD

**Issue by gkelly** [riscv/riscv-fesvr#10]
There's both a `LICENSE` and `COPYING` file in riscv-fesvr and riscv-pk.  Consolidating them into one file seems like it might make things clearer.  They're both BSD 3-clause, they just have slightly different formatting and names.

**Comment by sbeamer** [comment]
Maybe we should just remove COPYING since CB or MIT didn't work on RISC-V?

**Comment by aswaterman** [comment]
Yeah.
